name: Release

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run:  |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: pyinstaller --onefile -n MatanalHack main.py
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Build"
          files: |
            dist/*.exe
